/**
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
export const colors = {
    textLinkForeground: 'var(--vscode-textLink-foreground)',
    editorForeground: 'var(--vscode-editor-foreground)',
    indentGuideActiveBackgound: 'var(--vscode-editorIndentGuide-activeBackground)',
    vscodeForeground: 'var(--vscode-foreground)',
    vscodeDisabledForeground: 'var(--vscode-disabledForeground)',
    vscodeErrorForeground: 'var(--vscode-errorForeground)',
    vscodeDescriptionForeground: 'var(--vscode-descriptionForeground)',
    vscodeIconForeground: 'var(--vscode-icon-foreground)',
    vscodeFocusBorder: 'var(--vscode-focusBorder)',
    vscodeTextSeparatorForeground: 'var(--vscode-textSeparator-foreground)',
    vscodeTextLinkForeground: 'var(--vscode-textLink-foreground)',
    vscodeTextLinkActiveForeground: 'var(--vscode-textLink-activeForeground)',
    vscodeTextPreformatForeground: 'var(--vscode-textPreformat-foreground)',
    vscodeTextBlockQuoteBackground: 'var(--vscode-textBlockQuote-background)',
    vscodeTextBlockQuoteBorder: 'var(--vscode-textBlockQuote-border)',
    vscodeTextCodeBlockBackground: 'var(--vscode-textCodeBlock-background)',
    vscodeWidgetShadow: 'var(--vscode-widget-shadow)',
    vscodeWidgetBorder: 'var(--vscode-widget-border)',
    vscodeInputBackground: 'var(--vscode-input-background)',
    vscodeInputForeground: 'var(--vscode-input-foreground)',
    vscodeInputOptionActiveBorder: 'var(--vscode-inputOption-activeBorder)',
    vscodeInputOptionHoverBackground: 'var(--vscode-inputOption-hoverBackground)',
    vscodeInputOptionActiveBackground: 'var(--vscode-inputOption-activeBackground)',
    vscodeInputOptionActiveForeground: 'var(--vscode-inputOption-activeForeground)',
    vscodeInputPlaceholderForeground: 'var(--vscode-input-placeholderForeground)',
    vscodeInputValidationInfoBackground: 'var(--vscode-inputValidation-infoBackground)',
    vscodeInputValidationInfoBorder: 'var(--vscode-inputValidation-infoBorder)',
    vscodeInputValidationWarningBackground: 'var(--vscode-inputValidation-warningBackground)',
    vscodeInputValidationWarningBorder: 'var(--vscode-inputValidation-warningBorder)',
    vscodeInputValidationErrorBackground: 'var(--vscode-inputValidation-errorBackground)',
    vscodeInputValidationErrorBorder: 'var(--vscode-inputValidation-errorBorder)',
    vscodeDropdownBackground: 'var(--vscode-dropdown-background)',
    vscodeDropdownForeground: 'var(--vscode-dropdown-foreground)',
    vscodeDropdownBorder: 'var(--vscode-dropdown-border)',
    vscodeButtonForeground: 'var(--vscode-button-foreground)',
    vscodeButtonSeparator: 'var(--vscode-button-separator)',
    vscodeButtonBackground: 'var(--vscode-button-background)',
    vscodeButtonHoverBackground: 'var(--vscode-button-hoverBackground)',
    vscodeButtonSecondaryForeground: 'var(--vscode-button-secondaryForeground)',
    vscodeButtonSecondaryBackground: 'var(--vscode-button-secondaryBackground)',
    vscodeButtonSecondaryHoverBackground: 'var(--vscode-button-secondaryHoverBackground)',
    vscodeBadgeBackground: 'var(--vscode-badge-background)',
    vscodeBadgeForeground: 'var(--vscode-badge-foreground)',
    vscodeScrollbarShadow: 'var(--vscode-scrollbar-shadow)',
    vscodeScrollbarSliderBackground: 'var(--vscode-scrollbarSlider-background)',
    vscodeScrollbarSliderHoverBackground: 'var(--vscode-scrollbarSlider-hoverBackground)',
    vscodeScrollbarSliderActiveBackground: 'var(--vscode-scrollbarSlider-activeBackground)',
    vscodeProgressBarBackground: 'var(--vscode-progressBar-background)',
    vscodeEditorErrorForeground: 'var(--vscode-editorError-foreground)',
    vscodeEditorWarningForeground: 'var(--vscode-editorWarning-foreground)',
    vscodeEditorInfoForeground: 'var(--vscode-editorInfo-foreground)',
    vscodeEditorHintForeground: 'var(--vscode-editorHint-foreground)',
    vscodeSashHoverBorder: 'var(--vscode-sash-hoverBorder)',
    vscodeEditorBackground: 'var(--vscode-editor-background)',
    vscodeEditorStickyScrollBackground: 'var(--vscode-editorStickyScroll-background)',
    vscodeEditorStickyScrollHoverBackground: 'var(--vscode-editorStickyScrollHover-background)',
    vscodeEditorWidgetBackground: 'var(--vscode-editorWidget-background)',
    vscodeEditorWidgetForeground: 'var(--vscode-editorWidget-foreground)',
    vscodeEditorWidgetBorder: 'var(--vscode-editorWidget-border)',
    vscodeQuickInputBackground: 'var(--vscode-quickInput-background)',
    vscodeQuickInputForeground: 'var(--vscode-quickInput-foreground)',
    vscodeQuickInputTitleBackground: 'var(--vscode-quickInputTitle-background)',
    vscodePickerGroupForeground: 'var(--vscode-pickerGroup-foreground)',
    vscodePickerGroupBorder: 'var(--vscode-pickerGroup-border)',
    vscodeKeybindingLabelBackground: 'var(--vscode-keybindingLabel-background)',
    vscodeKeybindingLabelForeground: 'var(--vscode-keybindingLabel-foreground)',
    vscodeKeybindingLabelBorder: 'var(--vscode-keybindingLabel-border)',
    vscodeKeybindingLabelBottomBorder: 'var(--vscode-keybindingLabel-bottomBorder)',
    vscodeEditorSelectionBackground: 'var(--vscode-editor-selectionBackground)',
    vscodeEditorInactiveSelectionBackground: 'var(--vscode-editor-inactiveSelectionBackground)',
    vscodeEditorSelectionHighlightBackground: 'var(--vscode-editor-selectionHighlightBackground)',
    vscodeEditorFindMatchBackground: 'var(--vscode-editor-findMatchBackground)',
};
