name: Improvement Suggestion
description: Suggest a non-breaking improvement to an existing feature or workflow
title: "[Improvement] "
labels: [improvement]
body:
  - type: textarea
    id: related-problem
    attributes:
      label: Is your improvement related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
  - type: textarea
    id: improvement
    attributes:
      label: Describe the improvement you'd like
      description: A clear and concise description of the improvement or enhancement you are proposing.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or approaches you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the improvement suggestion here.
