name: Task
description: Request a specific task, update, or maintenance work
title: "[Task] "
labels: [task]
body:
  - type: textarea
    id: task-description
    attributes:
      label: Task description
      description: Clearly describe the task that needs to be completed.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: List the criteria that must be met for this task to be considered complete.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, references, or details related to this task here.
