name: Publish SI Extension to VSCode Marketplace and OpenVSX

on:
  workflow_dispatch:
    inputs:
      isPreRelease:
        required: true
        type: boolean 
        default: false
      vscode:
        description: Publish to VSCode marketplace
        type: boolean
        required: true
        default: false
      openVSX:
        description: Publish to OpenVSX marketplace
        type: boolean
        required: true
        default: false
      workflowRunId:
        required: true

jobs:
  publish:
    name: Publish SI extension to marketplaces
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.inputs.workflowRunId }}
          name: VSIX

      - name: Unzip
        run: |
          unzip VSIX.zip
          rm VSIX.zip

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - run: | 
          npm install -g vsce
          npm install -g ovsx

      - name: Get version
        id: vsix
        run: | 
          file=$(ls streaming-integrator-[0-9]*.[0-9]*.[0-9]*.vsix)
          fileName=${file##*-}
          version=${fileName%.*}
          echo "vsixName=$file" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          if [ "${{ github.event.inputs.isPreRelease }}" == "true" ]; then
            echo "releaseMode=--pre-release" >> $GITHUB_OUTPUT
          else
            echo "releaseMode= " >> $GITHUB_OUTPUT
          fi  

      - name: Publish to VSCode marketplace
        if: ${{ github.event.inputs.vscode == 'true' }}
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath ${{ steps.vsix.outputs.vsixName }} ${{ steps.vsix.outputs.releaseMode }}

      - name: Publish to OpenVSX marketplace
        if: ${{ github.event.inputs.openVSX == 'true' && github.event.inputs.isPreRelease == 'false' }}
        run: ovsx publish -p ${{ secrets.OPENVSX_TOKEN }} --packagePath ${{ steps.vsix.outputs.vsixName }} ${{ steps.vsix.outputs.releaseMode }}

      - name: Create a release in this repo
        run: |
          id=`curl -X GET  -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.vsix.outputs.version }} \
           | jq -r .id` && \
           updateResponse=`curl -X PATCH -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"draft":false,"prerelease":false}' \
            https://api.github.com/repos/${{ github.repository }}/releases/$id`         

      - name: "Release Notification"
        if: ${{ github.event.inputs.notify == 'true' }}
        run: |
          body=$(cat << EOF
          {
            "cards": [
              {
                "header": {
                    "title": "Marketplace Release",
                    "subtitle": "WSO2 Integrator: SI Extension"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "keyValue": {
                          "topLabel": "VSCode Marketplace",
                          "content": "v${{ steps.vsix.outputs.version }}",
                          "iconUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/512px-Visual_Studio_Code_1.35_icon.svg.png",
                          "button": {
                            "textButton": {
                              "text": "View",
                              "onClick": {
                                "openLink": {
                                  "url": "https://marketplace.visualstudio.com/items?itemName=WSO2.streaming-integrator"
                                }
                              }
                            }
                          }
                        }  
                      },
                      {
                        "keyValue": {
                          "topLabel": "OpenVSX Marketplace",
                          "content": "v${{ steps.vsix.outputs.version }}",
                          "iconUrl": "https://projects.eclipse.org/sites/default/files/open-vsx-logo-withouttext.png",
                          "button": {
                            "textButton": {
                              "text": "View",
                              "onClick": {
                                "openLink": {
                                  "url": "https://open-vsx.org/extension/wso2/streaming-integrator"
                                }
                              }
                            }
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF
          )
          curl \
            -X POST \
            -H 'Content-Type: application/json' \
            "${{ secrets.TOOLING_TEAM_CHAT_API }}" \
            -d "$body"
