name: Save build cache when PR merged

on:
  push:
    branches:
      - dev

env:
  ballerina_version: 2201.7.2

jobs:
  Build_Stage:
    name: Build repo
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: ${{ env.ballerina_version }}

      - name: Setup Rush
        uses: gigara/setup-rush@v1.2.0
        with:
          pnpm: 10.10.0
          node: 22.x
          rush-install: true
          rush-build: true
          optional-build-args: --verbose
